"""add_user_avatar_blob_and_email_verified_at

Revision ID: 16345e3cb02c
Revises: d7e8f9a0b1c2
Create Date: 2026-07-06 13:26:34.752871

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16345e3cb02c"
down_revision: Union[str, Sequence[str], None] = "d7e8f9a0b1c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_blob", sa.LargeBinary(), nullable=True))
    op.add_column(
        "users", sa.Column("avatar_mime_type", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("avatar_updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified_at")
    op.drop_column("users", "avatar_updated_at")
    op.drop_column("users", "avatar_mime_type")
    op.drop_column("users", "avatar_blob")
    # ### end Alembic commands ###
