"""add_user_ssh_keys_table

Revision ID: 3e9bd6ef019f
Revises: 16345e3cb02c
Create Date: 2026-07-06 13:55:15.355573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9bd6ef019f'
down_revision: Union[str, Sequence[str], None] = '16345e3cb02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ssh_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('key_type', sa.String(length=50), nullable=False),
    sa.Column('key_data', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('gitea_key_id', sa.String(length=36), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ssh_keys_fingerprint'), 'user_ssh_keys', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_user_ssh_keys_user_id'), 'user_ssh_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ssh_keys_user_id'), table_name='user_ssh_keys')
    op.drop_index(op.f('ix_user_ssh_keys_fingerprint'), table_name='user_ssh_keys')
    op.drop_table('user_ssh_keys')
    # ### end Alembic commands ###
