"""add project stars table

Revision ID: 41b04facde36
Revises: eb0cc60eef6f
Create Date: 2026-06-29 14:51:37.934170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "41b04facde36"
down_revision: Union[str, Sequence[str], None] = "eb0cc60eef6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_stars",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "project_id", name="uq_user_project_star"),
    )
    op.create_index(
        op.f("ix_project_stars_project_id"),
        "project_stars",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_stars_user_id"), "project_stars", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_stars_user_id"), table_name="project_stars")
    op.drop_index(op.f("ix_project_stars_project_id"), table_name="project_stars")
    op.drop_table("project_stars")
    # ### end Alembic commands ###
