"""add gitea oauth refresh fields

Revision ID: afd247718c46
Revises: 3e9bd6ef019f
Create Date: 2026-07-06 14:34:37.886444

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afd247718c46"
down_revision: Union[str, Sequence[str], None] = "3e9bd6ef019f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("gitea_refresh_token_encrypted", sa.Text(), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("gitea_token_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gitea_token_expires_at")
    op.drop_column("users", "gitea_refresh_token_encrypted")
    # ### end Alembic commands ###
