"""add gitea fields

Revision ID: d7e8f9a0b1c2
Revises: a1b2c3d4e5f6
Create Date: 2026-07-03 16:26:39.070109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e8f9a0b1c2'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('gitea_repo_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('gitea_full_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_projects_gitea_repo_id'), 'projects', ['gitea_repo_id'], unique=False)
    op.add_column('users', sa.Column('gitea_user_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('gitea_token_encrypted', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_gitea_user_id'), 'users', ['gitea_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_gitea_user_id'), table_name='users')
    op.drop_column('users', 'gitea_token_encrypted')
    op.drop_column('users', 'gitea_user_id')
    op.drop_index(op.f('ix_projects_gitea_repo_id'), table_name='projects')
    op.drop_column('projects', 'gitea_full_name')
    op.drop_column('projects', 'gitea_repo_id')
    # ### end Alembic commands ###
